### ISSUE TITLE
I got "in matMul: inputs must be rank 2" error when I used retained model.

### ISSUE THREAD

**Issue by zono** [google/emoji-scavenger-hunt#14] opened 2018-04-19 02:31 UTC
Hi I love Emoji Scavenger Hunt. I want to play the game with my own trained model. But I got the following error. Can you please help me?

**Summary**

I created a model and deployed it. However I got ```Error: Error in matMul: inputs must be rank 2, got ranks 1 and 2.``` error during starting the game. I want to solve it.

**Steps to Reproduce**

```
# Git clone from my forked repo
$ git clone --depth 1 --branch matmul-error https://github.com/y-zono/emoji-scavenger-hunt.git

# Training
$ cd emoji-scavenger-hunt/training/
$ docker build -t model-builder .
$ docker run -v /xxx/xxx/emoji-scavenger-hunt/training/data:/data -it model-builder

# Copy the trained files into dist
$ cp data/saved_model_web/group1-shard1of1 ../dist/model/group1-shard1of1
$ cp data/saved_model_web/tensorflowjs_model.pb ../dist/model/web_model.pb
$ cp data/saved_model_web/weights_manifest.json ../dist/model/weights_manifest.json

# Run the app
$ cd ..; yarn prep; yarn dev

# Open browser and click "LET'S PLAY"
http://localhost:3000
```

**Expected Results**

The game is started normally.

**Actual Results**

The following message was showed on the page.

```
It looks like your browser or device doesn’t support this experiment. It’s designed to work best on mobile (iOS/Safari or Android/Chrome). 😭
```

The following error was occurred at matmul.ts

```
Error: Error in matMul: inputs must be rank 2, got ranks 1 and 2.
```

https://github.com/tensorflow/tfjs-core/blob/master/src/ops/matmul.ts#L49

**Notes**

1. The versions are the following.

```
@tensorflow/tfjs-converter@0.1.0
@tensorflow/tfjs-core@0.6.0

tensorflow v1.7.0 for training
```

2. Chrome browser version is 65.0.3325.181(Official Build)(64bit)

3. The original trained model worked normally on my local PC.

4. I added some images into my own forked repo for training and changed some files like game.ts and scavenger_classes.ts.

https://github.com/google/emoji-scavenger-hunt/compare/master...y-zono:matmul-error

5. I downloaded the cat and dog images from image-net

```
$ wget http://www.image-net.org/api/text/imagenet.synset.geturls?wnid=n02123045 -O cat.txt
$ wget http://www.image-net.org/api/text/imagenet.synset.geturls?wnid=n02087122 -O dog.txt
$ i=0; for file in `head -100 cat.txt`;do wget $file -O cat-$i.jpg; let i++ ;done
$ i=0; for file in `head -100 dog.txt`;do wget $file -O dog-$i.jpg; let i++ ;done
```

**Comment by jbruwer** [comment] 2018-04-20 16:00
Hi thanks for trying our game and sorry you're having some issues. Seems like that error message is a little confusing but it looks like there might have been issues loading your re-trained model files.

@tushuhei - do you mind taking a look and see if this re-training should work as expected.

Thanks!

**Comment by tushuhei** [comment] 2018-04-21 04:36
Hi there,

I managed to reproduced the issue on my end. I believe this is the same issue as https://github.com/tensorflow/tfjs/issues/85 and I confirmed that my rebuilt model does not have `Reshape` op as well. I will try to migrate the fix advised in that thread into the Dockerfile as well.

Thanks,

**Comment by zono** [comment] 2018-04-21 14:26
@tushuhei @jbruwer Thank you for taking your time. I will also try to fix it.

**Comment by tushuhei** [comment] 2018-04-23 00:07
@y-zono I made a fix and pushed it to the branch [fix-reshape](https://github.com/google/emoji-scavenger-hunt/tree/fix-reshape). Feel free to try it out to see how it works.

**Comment by zono** [comment] 2018-04-23 01:45
@tushuhei The issue was solved. Thank you!

**Comment by tushuhei** [comment] 2018-04-24 04:10
Let me keep this issue open until #16 is merged or tensorflow/tfjs#85 is fixed to keep this visible for those who encountered the same issue.

**Comment by tushuhei** [comment] 2018-04-26 00:08
The upstream fix comes in version 0.2.0. https://github.com/tensorflow/tfjs-converter/pull/89
Will close this issue once it's released.

**Comment by tushuhei** [comment] 2018-04-26 06:46
Closing this since tfjs-converter 0.2.0 is now released.

**Comment by jbruwer** [comment] 2018-04-26 17:33
@tushuhei Should we update the dockerfile to remove the explicit branch flag now or does what we have in master right now work with the fixes applied upstream?

**Comment by tushuhei** [comment] 2018-04-27 01:03
@jbruwer Looks like the upstream issue is not fixed fully. I still see that the required op `reshape` is removed after conversion. I will follow up tensorflow/tfjs#85 on this.
We can keep the branch flag for tensorflow repo as is because it is to fix the path to retrain.py and separated from this issue.

**Closed as completed** 2018-05-10 23:01 UTC
