### ISSUE TITLE
"Browser or device doesn't support this experiment"?

### ISSUE THREAD

**Issue by Hellscream-25** [google/emoji-scavenger-hunt#41] opened 2018-11-07 11:21 UTC
![untitled](https://user-images.githubusercontent.com/44601128/48128448-738d3680-e2c1-11e8-96c1-9bdf45204267.png)

Hi I tried setting up this app using the available codes through VirtualBox Ubuntu 16.04 but it says "Browser or device doesn't support this experiment". The same thing appeared when I tried the online demo. However at my Windows OS (of the same device), the online demo works perfectly.  May I know what the problem actually is?

**Comment by jbruwer** [comment] 2018-11-08 00:46
It looks like the browser you are using on Ubuntu to view this does not support some of the functionality we need for the experiment. Can you post which browser and version you used on Ubuntu?

**Comment by Hellscream-25** [comment] 2018-11-09 08:22
Hi my chrome is of version 69.0.3497.100 while mozilla is 62.0.3 , both is of 64-bit

**Comment by tushuhei** [comment] 2018-11-09 09:20
Hi there,

Please make sure that the camera is accessible from the browser. The camera
connectivity is required to run this game.

Shuhei

2018年11月9日(金) 17:22 Hellscream-25 <notifications@github.com>:

**Comment by Hellscream-25** [comment] 2018-11-10 17:30
Hi
So ya I did not allow my VirtualBox to access my webcam but when I went for the USB settings in my VB (to allow it), my VB becomes unlaunchable. Looks like I need some extension pack or something but anyway thanks for the respond and I will try to get my VB back up and running to continue playing around with your emoji scavenger app. By any chances , is there a simple diagram / flowchart of how this app works?

**Comment by tushuhei** [comment] 2018-11-20 05:27
We've published a blog post to introduce the technical background of the game. This might be of some help.
https://medium.com/tensorflow/a-look-at-how-we-built-the-emoji-scavenger-hunt-using-tensorflow-js-3d760a7ebfe6

Since the issue is more of the VirtualBox settings, let me close this issue for now.

**Closed as completed by tushuhei** 2018-11-20 05:27 UTC

**Comment by Hellscream-25** [comment] 2018-11-20 17:32
Thanks for your help
